spring.application.name=backend

# H2 Database Configuration
spring.datasource.url=jdbc:h2:./data/job_tracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=5

# JWT
app.jwt.secret=12345678901234567890123456789012